feat: реализация ФП14 add-bookings
skyJetBrain/java-shareit pull request #2
Opened 2022-10-23 12:15 UTC by skyJetBrain

2022-10-23 17:43 UTC, eugene-lenkevich requested changes
Привет, Валерий, спасибо за PR

В целом все отлично, отметил небольшие моменты про транзакции и методы equals и hashCode для сущностей :)

2022-10-23 17:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
Этой аннотации надо указать по каким полям строить equals и hashCode

Вообще, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
https://habr.com/ru/post/268903/

2022-10-23 17:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +@Transactional
Все публичные методы этого сервиса будут выполняться в транзакциях. Если в случае изменения данных это правильно, то в случае селектов, которые не изменяют данные это будут просто лишние накладные расходы. Так что лучше этой аннотацией явно отмечать методы, меняющие данные (insert, update и delete ) :)

2022-10-23 17:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<Item> optionalItem = itemRepository.findById(itemId);
Item item = itemRepository.findById(itemId).orElseThrow( ()->... );

Чутка запись покороче :)

2022-10-24 11:53 UTC, skyJetBrain commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
Добавил во всех моделях по id @EqualsAndHashCode(of = "id")

2022-10-24 11:53 UTC, skyJetBrain commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +@Transactional
Добавил во всех сервисах

2022-10-24 11:53 UTC, skyJetBrain commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<Item> optionalItem = itemRepository.findById(itemId);
сделал покороче везде где ьможно было)
то есть во всех сервисах

2022-10-24 12:29 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2022-10-24 12:39 UTC, merged